### ISSUE TITLE
Ensuring validation rules, messages, and appliesIf can access data properly

### ISSUE THREAD

**Issue by jsobell** [grofit/treacherous#17]
OK, so something to consider here. Why would anyone ever want access to the model? Presumably only ever to access other properties.
So why do we resolve the property because we call the rule? To make it simpler to implement a rule because value is the thing to check (and it seems obvious at first glance).
So what happens if a rule needs to access another property. Well, firstly we have to tell the rule the *name* of the property, so we have to use the options. The rule either has to bodge a check of `mode[optionsOrValue]` or do it properly by instantiating a new PropertyResolver.
OK, so if we need this data when calling validate(), we also need it for withMessage and appliesIf, because we have no idea what they might want to access.

So if we have to hack in options and PRs, why not pass in the PR and the name of the property instead of value? Is there ever a situation where value is not the contents of a property?
I suppose it's a choice between model and PR. My question is, if Rules only ever need access to properties by name, why would be pass the model object itself?
Of course this means that as it stands, to use the PR you need to have both the model and the property string to resolve. Is it better to pass in a ModelResolver which includes the model reference?

We keep coming back to the old `FieldsMatchRule` example

```
    public validate(mr:ModelResolver, prop:string, optionsOrValue): Promise<boolean>
    {
        var result;
        var comparison = mr.get(optionsOrValue);
        var weakEquality = optionsOrValue.weakEquality || false;

        if(TypeHelper.isDateType(comparison))
        { result = ComparerHelper.dateTimeCompararer(mr.get(prop), comparison); }
        else
        { result = ComparerHelper.simpleTypeComparer(mr.get(prop), comparison, weakEquality); }

        return Promise.resolve(result);
    }

    public getMessage(value, optionsOrValue) {
        return `This field is ${mr.get(prop)} but should be equal to ${mr.get(optionsOrValue)}`;
    }
```

The only place this might not work is if the model contains functions, but to be honest I think that's a seriously edge-case, and there's nothing to stop us having `mr.model` available to cover that.

**Comment by grofit** [comment]
I dont see options and PRs as hacks, the options is just a placeholder to pass whatever you want (or dont want) into a validator, so a `maxLength` rule may want a numeric value representing the max length, a `require` validator may want a boolean specifying if it is required, then there may be really complex rules where you need to pass in multiple values, but its down to the rule consumer to specify what it requires, like something that did an async ajax request and wanted to know how much to throttle etc may need a json object passed in rather than a singular value.

Anyway getting to the crux of this, I dont see the model resolver adding anything that you don't already have access to. So lets take a theoretical `matches` rule where one property must match another:

```
import {PropertyResolver} from "property-resolver/index";
import {IValidationRule} from "./ivalidation-rule";

export class MatchesValidationRule implements IValidationRule
{
    public ruleName = "equal";

    constructor(private propertyResolver: PropertyResolver){}

    public validate(model, value, fieldToMatch: string): Promise<boolean>
    {
        if (fieldToMatch === undefined || fieldToMatch === null)
        { return Promise.resolve(false); }

        var matchingFieldValue = this.propertyResolver.resolveProperty(model, fieldToMatch);
        var result = matchingFieldValue === value;
        return Promise.resolve(result);
    }

    public getMessage(model, value, fieldToMatch: string) {
        var matchingFieldValue = this.propertyResolver.resolveProperty(model, fieldToMatch);
        return `This field is ${value} but should match ${matchingFieldValue}`;
    }
}
```

This assumes we are passing the model to rules, which is basically the same as your approach above but you have a wrapper around the model to assist with accessing it. So here we adhere to IoC and pass in the property resolver (as our rule option is going to be a property as a string), then we basically consume that via the property resolver.

`matches` is the only kind of rule type I can envision which would require a property as a string in common use-cases, so in most other cases where you want to alter validation logic based upon some state within the model you would generally just ask the model directly for the values you care about, like `model.isAdmin` or `model.currentOptionsChosen.length` or whatever.

The addition of model to the rules does complicate things more than I would like however it does keep it self contained and also allows complex use cases where you need to alter the underlying rule logic based upon composite state in the model.

The developer in me likes the idea of a model resolver which basically pre-packages the model and the property resolver, but in most cases its just an abstraction on something that doesnt need to be abstracted from my current perspective.

As always I am happy to discuss further if there are some strong points for this.

**Comment by grofit** [comment]
Given that we now have this notion of model resolver can this be closed?

**Comment by grofit** [comment]
I am closing this, you can re-open if you want.
