### ISSUE TITLE
modelStateChangedEvent is triggered incorrectly

### ISSUE THREAD

**Issue by MaximBalaganskiy** [grofit/treacherous#18]
The `modelStateChangedEvent` is triggered with `isValid==true` when not all properties are valid
[Gist](https://gist.run/?id=89e478227240a83c0ce4765526078846) - start entering one field and `isValid` immediately switches to `true`. If you then clear that field it stays `true`.

**Comment by grofit** [comment]
Have just checked this and it does look like some weird bug, will try to replicate in a test and will get back to you with a solution.

**Comment by grofit** [comment]
After taking a quick look I *think* the error is down to when it gets a property change from invalid to valid and it had errors on the model before it incorrectly assumes that all errors are now solved, which is incorrect, so it needs to quickly check if there are still outstanding errors, and if not then change the state.

I have made a test based upon your gist and have changed the code to solve it, so hopefully once jason and I figure out the next merge of his features we can look at adding the fix for this in.

**Comment by grofit** [comment]
Will close this as it should be fixed and released, feel free to re-open if not.
